/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4d847d2d-e0a8-473c-8eb9-2cafe73055f6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_JvMYIagTq",
    "aws_user_pools_web_client_id": "640sn31gad0af9ti7p1gumu6nq",
    "oauth": {}
};


export default awsmobile;
